services:
  paradb:
    build:
      context: ..
      args:
        - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
    container_name: paradb_server
    environment:
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - PGUSER=${PGUSER}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
    ports:
      - 3000:3000
    restart: unless-stopped
